# Generated by Django 6.0 on 2025-12-10 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriconnect', '0003_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutriconnect.farmer'),
        ),
    ]
