# Generated by Django 6.0 on 2025-12-10 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriconnect', '0004_produce_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produces', to='nutriconnect.farmer'),
        ),
    ]
