"""
Django settings for nutri project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+hrgh8@cwf7eta+#1&y&v$b$wotl5=her3sc0*9=1rxin^zg*!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'nutriconnect',
    'django_daraja',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nutri.urls'

# --- Authentication URL Settings ---

# URL where unauthenticated users are redirected when accessing a @login_required view.
LOGIN_URL = 'login'

# URL to redirect to after successful login (defaulting to the 'marketplace' page)
LOGIN_REDIRECT_URL = 'marketplace'

# URL to redirect to after successful logout (defaulting to the 'home' page)
LOGOUT_REDIRECT_URL = 'home'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nutri.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# =======================================================
# MPESA DARAJA SETTINGS (Replace placeholders with your actual keys)
# =======================================================

# Possible values: 'sandbox' or 'production'
MPESA_ENVIRONMENT = 'sandbox'

# Credentials from your Daraja App
MPESA_CONSUMER_KEY = 'GKwF29dNNAu5ofeteBSXu3hxjbe6r1c1tpOcEvnWleK8jTcz'
MPESA_CONSUMER_SECRET = 'yz78UtNsDnNGIEEMGIa6Kg70jHF5F3rblngJs6eYPcAeZwseJMzPBzB7Jh7igetsYOUR_CONSUMER_SECRET'

# For Lipa na M-PESA Online (STK Push)
MPESA_EXPRESS_SHORTCODE = '174379' # Use 174379 for Safaricom Sandbox
MPESA_PASSKEY = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ad71a808947' # Use the Sandbox 

# Public URL for callbacks (must be accessible from Safaricom's servers)
SITE_URL = os.environ.get('SITE_URL', 'https://yourdomain.com')
MPESA_API_URL = SITE_URL

# You must have a public URL for the callback. For testing, you must use NGROK or a similar service.
# For now, you can use a placeholder, but this must be a publicly accessible URL when you test.
MPESA_API_URL = 'YOUR_PUBLIC_HOST'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'